dbt_vanilla:
  outputs:
    dev:
      dataset: dbt_vanilla
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      priority: interactive
      project: datalab-434211
      keyfile: /secrets/dbt-service-keyfile
      threads: 8
      type: bigquery
    local:
      dataset: dbt_vanilla
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: datalab-434211
      threads: 8
      type: bigquery
  target: dev