name: Backend Docker Build

on:
    push:
        branches:
            - main
        paths:
            - "app/**"
            - "terraform/**"
            - "Dockerfile"
            - "requirements.txt"
            - ".github/workflows/backend.build.yaml"

env:
    GCP_PROJECT_ID: datalab-434211
    GCP_ZONE: europe-west1
    GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    IMAGE_NAME: dbt-test
    REPO_ARTIFACTORY: dbt-vanilla-repo
    TARGET_RESSOURCE_TERRAFORM_ARTIFACT_REGISTRY: google_artifact_registry_repository.my-repo

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Authenticate with Google Cloud
            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker ${{ env.GCP_ZONE}}-docker.pkg.dev --project=${{ env.GCP_PROJECT_ID }}

            # Initialisation of terraform
            - name: Terraform init
              run: |
                  cd terraform && terraform init -upgrade

            # Initialisation of terraform
            - name: Terraform plan for artifatory
              run: |
                  cd terraform && terraform plan -target=${{ env.TARGET_RESSOURCE_TERRAFORM_ARTIFACT_REGISTRY}} -var "github_sha=${GITHUB_SHA::7}" -lock=false

            # Initialisation of terraform
            - name: Terraform apply for for artifatory
              run: |
                  cd terraform && terraform apply --auto-approve -target=${{ env.TARGET_RESSOURCE_TERRAFORM_ARTIFACT_REGISTRY}} -var "github_sha=${GITHUB_SHA::7}" -lock=false

            # Build the artifact
            - name: Docker Build
              run: |
                  docker build . -t dbt_test:${GITHUB_SHA::7} --platform linux/amd64

            # Tag the artifact
            - name: Docker Tag
              run: |
                  docker tag dbt_test:${GITHUB_SHA::7} ${{ env.GCP_ZONE}}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_ARTIFACTORY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}

            # Publish the artifact
            - name: Docker Publish
              run: |
                  docker push ${{ env.GCP_ZONE}}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_ARTIFACTORY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}
            
            # Planification of terraform
            - name: Terraform plan
              run: |
                  cd terraform && terraform plan -var "github_sha=${GITHUB_SHA::7}" -lock=false

            # Deployment of terraform
            - name: Terraform apply
              run: |
                  cd terraform && terraform apply --auto-approve -var "github_sha=${GITHUB_SHA::7}" -lock=false